server:
  port: 8001

spring:
#  resources:
#    static-locations: D:/MEITU/

  jetbrick:
    template:
      # 是否启用页面缓存
      cache: false
      # 页面默认编码方式，默认utf-8
      charset: UTF-8
      # 该属性必须配置为true，不然不会加载改视图处理器
      # 没有特别要求其他默认即可
      enabled: true
      # 该试图处理器的优先级，默认最低
      order: 1
      # 视图类型，默认text/html
      content-type: text/html
      # 默认 templates/
      prefix: templates/
      # 默认 .html
      suffix: .html
      # 一个map配置集合
      config:
      jetx.autoscan.packages: cn.bhshare.meitu

mybatis:
  type-aliases-package: cn.bhshare.meitu.model
  mapper-locations: classpath:mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

logging:
  level:
    cn.bhshare.meitu.dao: debug

#multipart:
#  enabled: true
#  #location: roy-upload-tmp
#  max-file-size: 100MB
#  max-request-size: 100MB
